export const ROUTES = {
  home: "/",
  products: "/products",
  aboutUs: "/about-us",
  feedbacks: "/feedbacks",
  login: "/login",
  register: "/register",
  myDesigns: "/designs/my",
  designEditor: "/designs/:designId/editor",
  tryOn: "/tryon/:designId",
  tryOnResult: "/tryon/result/:requestId",
  checkout: "/checkout/:designId",
  payment: "/payment/:orderId",
  paymentSuccess: "/payment/success",
  paymentCancel: "/payment/cancel",
  myOrders: "/orders/my",
  orderDetail: "/orders/:orderId",
  submitFeedback: "/orders/:orderId/feedback",
  staff: "/staff",
  staffOrders: "/staff/orders",
  staffOrderDetail: "/staff/orders/:orderId",
  staffPrintInfo: "/staff/orders/:orderId/print-info",
  staffFeedbacks: "/staff/feedbacks",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
} as const;
